apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminology-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terminology-service
  template:
    metadata:
      labels:
        app: terminology-service
    spec:
      containers:
      - name: terminology-service
        image: ghcr.io/gravitate-health/terminology-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
