{{- if and (eq .Values.networking.type "istio") .Values.networking.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "terminology-service.fullname" . }}
  labels:
    {{- include "terminology-service.labels" . | nindent 4 }}
spec:
  selector:
    {{- toYaml .Values.networking.istio.gateway.selector | nindent 4 }}
  servers:
  {{- range .Values.networking.istio.gateway.servers }}
  - port:
      number: {{ .port.number }}
      name: {{ .port.name }}
      protocol: {{ .port.protocol }}
    hosts:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
    {{- if .tls }}
    tls:
      {{- toYaml .tls | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
